### PR TITLE
fix #571 - don't check component dependency override when deserializing

### LINKED ISSUE #571: Dependencies always override "existing" views
It's really great to finally have view dependencies in Derby! However, [this](https://github.com/derbyjs/derby/blob/2819411a7d0b2a4b8ac3bcab7f594a5d0a5d5c27/lib/App.js#L239) exception creates a problem: on the server, everything works and Derby serializes the views, then the client registers the serialized views. After that, the client executes the component code, tries to add the dependencies (again) and throws this error.

I think a solution might be to check if we are in a server context and only then throw this error--unless it is possible to create new view only on the client.

### PR DESCRIPTION
**Pull request by nateps**
Quick fix for issue #571. Not sure if there is a more elegant way to do this, but this seems to work well.

### CODE REVIEW

File: lib/App.js [hunk 1]
```diff
@@ -235,7 +235,7 @@ App.prototype.component = function(name, constructor, isDependency) {
 
   // Calling app.component() overrides existing views or components. Prevent
   // dependencies from doing this without warning
-  if (isDependency && currentView) {
+  if (isDependency && currentView && !serializedViews) {
```
Comment (ericyhwang) [inline lib/App.js]: This change causes the error never be thrown, since `serializedViews` is an empty module on the server and thus is truthy:

```
$ node
> require('./lib/_views')
{}
> !!require('./lib/_views')
true
```

In a client using serialized views, [the variable's a function](https://github.com/derbyjs/derby/blob/v0.10.24/lib/App.js#L56), so `var usingSerializedViews = typeof serializedViews === 'function';` at module level could work.
